<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Evydencia.PhotoSelector.Application\Evydencia.PhotoSelector.Application.csproj" />
    <ProjectReference Include="..\..\src\Evydencia.PhotoSelector.Imaging\Evydencia.PhotoSelector.Imaging.csproj" />
    <ProjectReference Include="..\..\src\Evydencia.PhotoSelector.Infrastructure\Evydencia.PhotoSelector.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Evydencia.PhotoSelector.Storage\Evydencia.PhotoSelector.Storage.csproj" />
  </ItemGroup>

</Project>
